### PR TITLE
Updated the contributing.md #issue7

### PR DESCRIPTION
**Pull request by mhamzanadeem**
@CS50X-RGB  I am participating in hacktober 2023. I have updated the contributing .md as per your request . You can review my contribution. If it require changes , just put a reply

### CODE REVIEW

**Comment by CS50X-RGB** [comment]
All is cool just add your name and profile pic in the README.md @mhamzanadeem

**Review by CS50X-RGB — CHANGES_REQUESTED** [review]
Just Add your name in the REDAME.md file

**Comment by mhamzanadeem** [comment]
@CS50X-RGB  i have added my name in readme.md file

**Review by CS50X-RGB — APPROVED** [review]
Cool @mhamzanadeem

**Pull request merged**
