### PR TITLE
Create a Issue and Pull Request template for the new contributors #11

### PR DESCRIPTION
**Pull request by mhamzanadeem**
@CS50X-RGB I have made templates  for issue

### CODE REVIEW

**Review by CS50X-RGB — CHANGES_REQUESTED** [review]
Just add one file for pull request too

**Comment by CS50X-RGB** [comment]
@mhamzanadeem Work on the review message and link this to the CONTRIBUTION.md

**Comment by mhamzanadeem** [comment]
@CS50X-RGB I have made changes as per your request

**Review by CS50X-RGB — APPROVED** [review]
@mhamzanadeem Cool :)

**Comment by CS50X-RGB** [comment]
Closes #11

**Pull request merged**
